# Generated by Django 3.0.6 on 2020-05-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200523_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated', '-timestamp', '-publish_date']},
        ),
    ]
